# we need memory limits, they're only available in 2.*
version: '2'

services:
  node:
    build: 
      context: .
      dockerfile: ./cmd/node-server/Dockerfile
    ports: 
      - 8080:8080
    mem_limit: 128m
    volumes: 
      - ./cmd/node-server/:/opt/
    command: node --max_old_space_size=80 lib.js
  runtime:
    build:
      context: ./cmd/runtime
      dockerfile: ./Dockerfile
    image: maxmcd/wasm-servers:runtime
  circleci:
    build:
      context: ./cmd/circleci-runner
      dockerfile: ./Dockerfile
    image: maxmcd/wasm-servers:circleci
  go:
    build:
      context: ./pkg/go/
      dockerfile: ./Dockerfile
    image: maxmcd/wasm-servers:go
  go-print:
    build:
      context: ./cmd
      dockerfile: ./go-print/Dockerfile
    image: maxmcd/wasm-servers:go-print
  rust-basic:
    build:
      context: ./cmd/rust-basic
      dockerfile: ./Dockerfile
    image: maxmcd/wasm-servers:rust-basic
